### ISSUE TITLE
Jacquard Syntax

### ISSUE THREAD

**Issue by CrmsnDragoon** [sekwah41/DarkRoomFanPatch#1]
Good work on the patch!

The tech director for the game made pains to ensure that the tooling was open sourced (this is far from the usual for games)

I no longer have a list of usable functions, or the game script source, but the binary format used by Jacquard can be found here: https://github.com/StirfireStudios/Jacquard-YarnCompiler
And the tool we made and used to make the game can be found here: https://github.com/StirfireStudios/Jacquard

And you could probably use those to get the function names that the game supports to work from there.

If there is a bug with the game I'm sorry we couldn't catch it during the debugging process, but rent needed to be paid, and developer time isn't free.

Also I'm pretty sure the crash bug is in the Jacquard runtime that was made in Unreal 4 C++ so you are probably not going to be able to fix that one easily, and the source of that didn't make it to any public repo.

I wish you and all Darrens luck, and I hope this post was useful.

**Comment by skylarkblue1** [comment]
Hello!

We found Jacquard near the start of the project, this page in particular helped us a ton in being able to mostly read the code we have access to: https://github.com/StirfireStudios/Jacquard-YarnCompiler/blob/master/src/commands.js#L9 so thank you for making it open source!

We understand that bugs are normal in games, (afterall, we've played and made enough of them ourselves!), but some bugs detract from the experience and in some cases like the one with the achievement, it stops people from fully completing the game.
I found your tweet you made about us (https://twitter.com/CrmsnDragoon/status/1245996645143031811) and I would like to correct you on a couple things. First of all, the achievement was unobtainable due to at most 3 reasons.

1) The code saves to 1 variable, then loads from another therefor the game never counts up the correct variable that the achievement call checks.
2) There's a typo for "achievement" in the call, instead it's "achivement"
3) The achievement call name is missing the first part of it. We tested this name to see if it could be forced to get called, and the achievement didn't get given so even without the other 2 issues, it could never be called.

We didn't change how the achievement is obtained, we also haven't said *how* to obtain it so people can find out for themselves. It's still as difficult as intended, unless the intended way was via an achievement manager which probably isn't the best idea.

**Comment by CrmsnDragoon** [comment]
OK, so admittedly it was 2 years ago, but I think the code was supposed to be something like:

Enter node Start
Go to Node A
Enter node A
A:
- choose between two nodes B and C:
- Go to choice

B:
- Counter increases by counter + 1
- If achievement total reached, fire achievement method with the achievement name set
- Choose between D and A
- go to choice

C: 
- reset count
- go to next

D:
- reset count 
- go to next

We don't have an opcode that matches exactly to +=, so that's why it may look like the code is resetting the variable, though expect you already know that.

I totally believe that a typo caused this bug, it was a source of a lot of bugs in the game, and the reason is also not interesting: our tooling didn't have a way to check for invalid names of C++ functions, and that was a huge pain for a lot of the project. (we also didn't have a way to check parameter names, so I'm glad that that wasn't the issue, because it would be guesswork to find the real name)

I do find it interesting that this popped up, because I did test it with the total check set to [Small value] before setting it to [Large value] to commit the change. (Which was in fact the value that the designer wanted)
Steam allows you to reset progress on an achievement to test it, so at least at some point it did work, though the blame for it not working is definitely my fault, and I'm sorry this oversight happened at all, let alone by my mistake.

**Comment by sekwah41** [comment]
The issue isn't that it's resetting. It's that it's storing to a completely separate variable.
they are both named `idontsee` but one uses underscores and the other doesn't. The code is loading the variable from one and saving to the other hence the logic loop is never completed.

I verified the rest of the code by rewriting it to call from other positions but aside from the misspelling of the achievement the beginning of the achievement label was missing `ach_` and was only `l1_12_kafka`.

The changes we make litteraly fix the typo in the method, add `ach_` by deleting some of the misspelt call which luckily is next to the achievement name so we get to butcher that to free up space so the pak file doesn't become larger causing the game to crash when loading.

The other changes just alter the references to the variables to be the same so that the alternative `idontsee` doesn't get used.

This isn't an attack on any of the work you did and we understand mistakes are made but rather we just saw a small issue and wanted to play with it to see if we can fix issues in a system we didn't know how it was made.
